import '../models/task_models.dart';

const List<AssistantTaskDefinition> defaultTaskDefinitions = [
  AssistantTaskDefinition(
    id: 'feed_am',
    kind: AssistantTaskKind.feedWindow,
    title: '上午刷视频',
    targetCount: 120,
    chunkMinutes: 5,
    startHour: 8,
    startMinute: 0,
    endHour: 12,
    endMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'feed_pm',
    kind: AssistantTaskKind.feedWindow,
    title: '下午刷视频',
    targetCount: 120,
    chunkMinutes: 5,
    startHour: 16,
    startMinute: 0,
    endHour: 20,
    endMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'ads',
    kind: AssistantTaskKind.adCooldown,
    title: '广告提醒',
    targetCount: 20,
    cooldownMinutes: 10,
    startHour: 8,
    startMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'quiz',
    kind: AssistantTaskKind.fixedPoint,
    title: '10:50 进入答题页',
    startHour: 10,
    startMinute: 50,
  ),
  AssistantTaskDefinition(
    id: 'fixed_10',
    kind: AssistantTaskKind.fixedPoint,
    title: '10:00 指定页面按钮',
    startHour: 10,
    startMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'fixed_12',
    kind: AssistantTaskKind.fixedPoint,
    title: '12:00 指定页面按钮',
    startHour: 12,
    startMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'fixed_14',
    kind: AssistantTaskKind.fixedPoint,
    title: '14:00 指定页面按钮',
    startHour: 14,
    startMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'fixed_16',
    kind: AssistantTaskKind.fixedPoint,
    title: '16:00 指定页面按钮',
    startHour: 16,
    startMinute: 0,
  ),
  AssistantTaskDefinition(
    id: 'fixed_18',
    kind: AssistantTaskKind.fixedPoint,
    title: '18:00 指定页面按钮',
    startHour: 18,
    startMinute: 0,
  ),
];
